/*
 * MDMA_Configurations.h
 *
 *  Created on: Sep 17, 2023
 *      Author: Hesham Yasser
 */

#ifndef MDMA_CONFIGURATIONS_H_
#define MDMA_CONFIGURATIONS_H_

/***************************************DMA1 Configurations**********************************/
#define MDMA1_STREAM_CONFIGURED							4
/*
 * MDMA1_MEMORY_BURST_MODE :-
 	 * MDMA_SINGLE_TRANSFER
 	 * MDMA_INCR4
 	 * MDMA_INCR8
 	 * MDMA_INCR16
 */
#define MDMA1_MEMORY_BURST_MODE							MDMA_SINGLE_TRANSFER
/*
 * MDMA1_PERIPHERAL_BURST_MODE :-
 	 * MDMA_SINGLE_TRANSFER
 	 * MDMA_INCR4
 	 * MDMA_INCR8
 	 * MDMA_INCR16
 */
#define MDMA1_PERIPHERAL_BURST_MODE						MDMA_SINGLE_TRANSFER
/*
 * MDMA1_DOUBLE_BUFFER_MODE :-
 	 * MDMA_DOUBLE_BUFFER_ON
 	 * MDMA_DOUBLE_BUFFER_OFF
 */
#define MDMA1_DOUBLE_BUFFER_MODE						MDMA_DOUBLE_BUFFER_OFF
/*
 * MDMA1_PRIORITY :-
 	 * MDMA_PRIORITY_LOW
 	 * MDMA_PRIORITY_MED
 	 * MDMA_PRIORITY_HIGH
 	 * MDMA_PRIORITY_VHIGH
 */
#define MDMA1_PRIORITY									MDMA_PRIORITY_LOW
/*
 * MDMA1_PERIPHERAL_INCREMENT_SIZE :-
 	 * MDMA_SIZE_LINKED_PSIZE
 	 * MDMA_SIZE_FIXED_4BYTE
 */
#define MDMA1_PERIPHERAL_INCREMENT_SIZE					MDMA_SIZE_LINKED_PSIZE
/*
 * MDMA1_MEMORY_INCREMENT_MODE
 	 * MDMA_POINTER_FIXED
 	 * MDMA_POINTER_INCREMENTED
 */
#define MDMA1_MEMORY_INCREMENT_MODE						MDMA_POINTER_FIXED
/*
 * MDMA1_PERIPHERAL_INCREMENT_MODE
 	 * MDMA_POINTER_FIXED
 	 * MDMA_POINTER_INCREMENTED
 */
#define MDMA1_PERIPHERAL_INCREMENT_MODE					MDMA_POINTER_FIXED
/*
 * MDMA1_CIRCULAR_MODE :-
 	 * MDMA_CIRCULAR_MODE_ENABLED
 	 * MDMA_CIRCULAR_MODE_DISABLED
 */
#define MDMA1_CIRCULAR_MODE								MDMA_CIRCULAR_MODE_DISABLED
/*
 * MDMA1_DATA_TRANSFER_DIRECTION :-
 	 * MDMA_PERIPHERAL_TO_MEMORY
 	 * MDMA_MEMORY_TO_PERIPHERAL
 	 * MDMA_MEMORY_TO_MEMORY
 */
#define MDMA1_DATA_TRANSFER_DIRECTION					MDMA_MEMORY_TO_PERIPHERAL
/*
 * MDMA1_PERIPHERAL_FLOW_CONTROLLER :-
 	 * MDMA_DMA_CONTROLLER
 	 * MDMA_PERIPHERAL_CONTROLLER
 */
#define MDMA1_PERIPHERAL_FLOW_CONTROLLER				MDMA_DMA_CONTROLLER
/*
 * MDMA1_TRANSFER_COMPLETE_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA1_TRANSFER_COMPLETE_INTERRUPT_STATE			MDMA_INTERRUPT_DISABLED
/*
 * MDMA1_HALF_TRANSFER_COMPLETE_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA1_HALF_TRANSFER_COMPLETE_INTERRUPT_STATE	MDMA_INTERRUPT_DISABLED
/*
 * MDMA1_TRANSFER_ERROR_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA1_TRANSFER_ERROR_INTERRUPT_STATE			MDMA_INTERRUPT_DISABLED
/*
 * MDMA1_DIRECT_MODE_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA1_DIRECT_MODE_INTERRUPT_STATE				MDMA_INTERRUPT_DISABLED
/*
 * MDMA1_FIFO_ERROR_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA1_FIFO_ERROR_INTERRUPT_STATE				MDMA_INTERRUPT_DISABLED
/*
 * MDMA1_DIRECT_MODE :-
 	 * MDMA_DIRECT_MODE_ENABLED
 	 * MDMA_DIRECT_MODE_DISABLED
 */
#define MDMA1_DIRECT_MODE								MDMA_DIRECT_MODE_ENABLED
/*
 * MDMA1_FIFO_THRESHOLD
 	 * MDMA_FIFO_BY_1
 	 * MDMA_FIFO_BY_2
 	 * MDMA_FIFO_BY_3BY4
 	 * MDMA_FIFO_BY_4
 */
#define MDMA1_FIFO_THRESHOLD							MDMA_FIFO_BY_1

/***************************************DMA2 Configurations**********************************/
#define MDMA2_STREAM_CONFIGURED							0
/*
 * MDMA2_MEMORY_BURST_MODE :-
 	 * MDMA_SINGLE_TRANSFER
 	 * MDMA_INCR4
 	 * MDMA_INCR8
 	 * MDMA_INCR16
 */
#define MDMA2_MEMORY_BURST_MODE							MDMA_SINGLE_TRANSFER
/*
 * MDMA2_PERIPHERAL_BURST_MODE :-
 	 * MDMA_SINGLE_TRANSFER
 	 * MDMA_INCR4
 	 * MDMA_INCR8
 	 * MDMA_INCR16
 */
#define MDMA2_PERIPHERAL_BURST_MODE						MDMA_SINGLE_TRANSFER
/*
 * MDMA2_DOUBLE_BUFFER_MODE :-
 	 * MDMA_DOUBLE_BUFFER_ON
 	 * MDMA_DOUBLE_BUFFER_OFF
 */
#define MDMA2_DOUBLE_BUFFER_MODE						MDMA_DOUBLE_BUFFER_OFF
/*
 * MDMA2_PRIORITY :-
 	 * MDMA_PRIORITY_LOW
 	 * MDMA_PRIORITY_MED
 	 * MDMA_PRIORITY_HIGH
 	 * MDMA_PRIORITY_VHIGH
 */
#define MDMA2_PRIORITY									MDMA_PRIORITY_LOW
/*
 * MDMA2_PERIPHERAL_INCREMENT_SIZE :-
 	 * MDMA_SIZE_LINKED_PSIZE
 	 * MDMA_SIZE_FIXED_4BYTE
 */
#define MDMA2_PERIPHERAL_INCREMENT_SIZE					MDMA_SIZE_LINKED_PSIZE
/*
 * MDMA2_MEMORY_INCREMENT_MODE
 	 * MDMA_POINTER_FIXED
 	 * MDMA_POINTER_INCREMENTED
 */
#define MDMA2_MEMORY_INCREMENT_MODE						MDMA_POINTER_INCREMENTED
/*
 * MDMA2_PERIPHERAL_INCREMENT_MODE
 	 * MDMA_POINTER_FIXED
 	 * MDMA_POINTER_INCREMENTED
 */
#define MDMA2_PERIPHERAL_INCREMENT_MODE					MDMA_POINTER_INCREMENTED
/*
 * MDMA2_CIRCULAR_MODE :-
 	 * MDMA_CIRCULAR_MODE_ENABLED
 	 * MDMA_CIRCULAR_MODE_DISABLED
 */
#define MDMA2_CIRCULAR_MODE								MDMA_CIRCULAR_MODE_DISABLED
/*
 * MDMA2_DATA_TRANSFER_DIRECTION :-
 	 * MDMA_PERIPHERAL_TO_MEMORY
 	 * MDMA_MEMORY_TO_PERIPHERAL
 	 * MDMA_MEMORY_TO_MEMORY
 */
#define MDMA2_DATA_TRANSFER_DIRECTION					MDMA_MEMORY_TO_MEMORY
/*
 * MDMA2_PERIPHERAL_FLOW_CONTROLLER :-
 	 * MDMA_DMA_CONTROLLER
 	 * MDMA_PERIPHERAL_CONTROLLER
 */
#define MDMA2_PERIPHERAL_FLOW_CONTROLLER				MDMA_DMA_CONTROLLER
/*
 * MDMA2_TRANSFER_COMPLETE_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA2_TRANSFER_COMPLETE_INTERRUPT_STATE			MDMA_INTERRUPT_ENABLED
/*
 * MDMA2_HALF_TRANSFER_COMPLETE_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA2_HALF_TRANSFER_COMPLETE_INTERRUPT_STATE	MDMA_INTERRUPT_DISABLED
/*
 * MDMA2_TRANSFER_ERROR_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA2_TRANSFER_ERROR_INTERRUPT_STATE			MDMA_INTERRUPT_DISABLED
/*
 * MDMA2_DIRECT_MODE_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA2_DIRECT_MODE_INTERRUPT_STATE				MDMA_INTERRUPT_DISABLED
/*
 * MDMA2_FIFO_ERROR_INTERRUPT_STATE :-
 	 * MDMA_INTERRUPT_ENABLED
 	 * MDMA_INTERRUPT_DISABLED
 */
#define MDMA2_FIFO_ERROR_INTERRUPT_STATE				MDMA_INTERRUPT_DISABLED
/*
 * MDMA2_DIRECT_MODE :-
 	 * MDMA_DIRECT_MODE_ENABLED
 	 * MDMA_DIRECT_MODE_DISABLED
 */
#define MDMA2_DIRECT_MODE								MDMA_DIRECT_MODE_ENABLED
/*
 * MDMA2_FIFO_THRESHOLD
 	 * MDMA_FIFO_BY_1
 	 * MDMA_FIFO_BY_2
 	 * MDMA_FIFO_BY_3BY4
 	 * MDMA_FIFO_BY_4
 */
#define MDMA2_FIFO_THRESHOLD							MDMA_FIFO_BY_1

#endif /* MDMA_CONFIGURATIONS_H_ */
